### ISSUE TITLE
The instance create form should expand on add

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#4058]
In the instance create form you can add elements to lists. When an element is added when the list is still closed, you need to first open the list to see it.

The goal is to expand on add when the list is not expanded yet.

[Screencast from 09-20-2022 06:12:25 AM.webm](https://user-images.githubusercontent.com/10819/191166016-8cf6c4fd-aa75-4d25-b5bb-eb1645eb7f2e.webm)

When a subitem only contains one field, it should open.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4058?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by LauraStordeur** [comment]
Placing this one to the Icebox. We've both tried different approaches, but the Virtual Dom is caching the element responsible for the collapsible section. This element is maintained and provided by Patternfly and doesn't provide inherent support for expanding the section once the component has been rendered a first time. 

- We can make it so that the component is always opened on initial render, but we can't do it on 'add' specifically. Even triggering the re-render with a callback doesn't do the trick.

- We could provide a different form of user feedback though, we could make the text bold eventually, or show a toast notification. 

@bartv
