### ISSUE TITLE
Composer - Ellipsing is behaving weirdly.

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5126]
The ellipsing doesn't look consistent at first glance, maybe see if we can adjust the behavior to our liking.

**Comment by matborowczyk** [comment]
I disabled initial ellipsing that is provided by jointJS team, and hardlocked it to ellipse if value is longer that 12, now inconsistencies that were left are due to the width of given text, but I don't have idea how to resolve it yet. @LukasStordeur 

Example of what we have at the moment(don't mind validity of the values provided there):
![Image](https://github.com/inmanta/web-console/assets/113331659/feca3c32-ec0b-4cc9-a0f4-504a70cf8266)

**Comment by LukasStordeur** [comment]
font to monospace; an adjust the width of the boxes.
